TortenkreationSHSBlog/Models/ListViewModel.cs
namespace TortenkreationSHSBlog.Models {

    using System.Collections.Generic;

    public class ListViewModel {

        public Occasion? Occasion { get; set; }

        public IEnumerable<Picture> Pictures { get; set; }

        public ListViewModel() {
            //nothing to do
        }

    }

}

TortenkreationSHSBlog/Models/Picture.cs
namespace TortenkreationSHSBlog.Models {

    using System;
    using System.IO;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Text.RegularExpressions;
    using System.Threading.Tasks;

    public class Picture {

        public readonly int ThumbnailWidth = 400;
        public readonly int ThumbnailHeight = 300;

        public int Id { get; set; }

        public DateTimeOffset CreatedAt { get; set; }

        public string Title { get; set; }

        public byte[] File { get; set; }

        public byte[] ThumbnailFile { get; set; }

        public string ContentType { get; set; }

        public string Extension { get; set; }

        public Occasion Occasion { get; set; }

        public bool IsPublished { get; set; }

        public Picture() {
            this.CreatedAt = new DateTimeOffset(DateTime.Now);
        }

        public Picture(CreatePictureViewModel pictureViewModel) : this() {
            this.Title = pictureViewModel.Title;
            this.Occasion = pictureViewModel.Occasion;
            this.ContentType = pictureViewModel.File.ContentType;
            this.Extension = Path.GetExtension(pictureViewModel.File.FileName);
            this.File = pictureViewModel.GetFileAsByteArray();
            this.IsPublished = pictureViewModel.IsPublished;
        }

        public string GetUrl() {
            var filePath = (this.Title + this.Extension).ToLower();
            filePath = Regex.Replace(filePath, "ö", "oe");
            filePath = Regex.Replace(filePath, "ä", "ae");
            filePath = Regex.Replace(filePath, "ü", "ue");
            filePath = Regex.Replace(filePath, "ß", "ss");
            filePath = Regex.Replace(filePath, @"[^a-z0-9\s-.]", "");
            filePath = Regex.Replace(filePath, @"\s+", " ").Trim();
            filePath = Regex.Replace(filePath, @"\s", "-");
            return filePath;
        }

        public async Task GenerateThumbnail(string apiKey) {
            var url = $@"https://westeurope.api.cognitive.microsoft.com/vision/v1.0/generateThumbnail?width={ThumbnailWidth}&height={ThumbnailHeight}&smartCropping=true";
            using (HttpClient client = new HttpClient()) {
                client.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", apiKey);
                using (ByteArrayContent content = new ByteArrayContent(this.File)) {
                    content.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
                    HttpResponseMessage response = await client.PostAsync(url, content);
                    if (response.IsSuccessStatusCode) {
                        this.ThumbnailFile = await response.Content.ReadAsByteArrayAsync();
                    } else {
                        throw new HttpRequestException("Thumbnail-Generierung fehlgeschlagen");
                    }
                }
            }
        }

        public void UpdateFrom(EditPictureViewModel picture) {
            this.Title = picture.Title;
            this.Occasion = picture.Occasion;
            this.IsPublished = picture.IsPublished;
            return;
        }

    }

}

TortenkreationSHSBlog/Controllers/PicturesController.cs
namespace TortenkreationSHSBlog.Controllers {

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Options;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Threading.Tasks;
    using TortenkreationSHSBlog.Models;
    using TortenkreationSHSBlog.Persistence;

    public class PicturesController : Controller {

        private readonly IPictureRepository pictureRepository;
        private readonly AppConfiguration appSettings;
        private readonly int MAX_BYTES = 5 * 1024 * 1024; //5MB
        private readonly string[] ACCEPTED_FILE_TYPES = new[] { ".jpg", ".jpeg", ".png", ".tif", ".bmp" };

        public PicturesController(IPictureRepository pictureRepository, IOptions<AppConfiguration> appSettings) : base() {
            this.pictureRepository = pictureRepository;
            this.appSettings = appSettings.Value;
        }

        [HttpGet, Authorize]
        public IActionResult Create() {
            var pictureViewModel = new CreatePictureViewModel();
            return View(pictureViewModel);
        }

        [HttpPost, Authorize, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreatePictureViewModel viewModel) {
            if (!ModelState.IsValid) {
                return View(viewModel);
            }
            if (viewModel.File == null || viewModel.File?.Length == 0) {
                ModelState.AddModelError("File", "Foto ungültig/leer.");
                return View(viewModel);
            }
            if (!this.ACCEPTED_FILE_TYPES.Any(s => s == Path.GetExtension(viewModel.File.FileName).ToLower())) {
                ModelState.AddModelError("File", "Foto-Dateiformat nicht erlaubt (nur JPG, PNG, BMP oder GIF).");
                return View(viewModel);
            }
            if (viewModel.File.Length > this.MAX_BYTES) {
                ModelState.AddModelError("File", "Foto darf nicht größer als 5MB sein.");
                return View(viewModel);
            }
            if (await this.pictureRepository.IsTitleExisting(viewModel.Title)) {
                ModelState.AddModelError("Title", "Titel bereits vergeben.");
                return View(viewModel);
            }
            var picture = new Picture(viewModel);
            await picture.GenerateThumbnail(appSettings.ApiKey);
            await this.pictureRepository.Add(picture);
            return RedirectToAction("List");
        }

        [HttpGet, Authorize]
        public async Task<IActionResult> Delete(int id) {
            var picture = await this.pictureRepository.GetById(id);
            if (null == picture) {
                return NotFound();
            }
            var viewModel = new EditPictureViewModel(picture);
            return View(viewModel);
        }

        [HttpPost, Authorize, ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, EditPictureViewModel viewModel) {
            var picture = await this.pictureRepository.GetById(id);
            if (null == picture || picture?.Id != id) {
                return NotFound();
            }
            await this.pictureRepository.Delete(picture);
            return RedirectToAction("List");
        }

        [HttpGet, AllowAnonymous]
        public async Task<IActionResult> Detail(string pictureUrl) {
            var picture = await this.pictureRepository.GetByUrl(pictureUrl);
            if (null == picture) {
                return NotFound();
            }
            return File(picture.File, picture.ContentType);
        }

        [HttpGet, Authorize]
        public async Task<IActionResult> Edit(int id) {
            var picture = await this.pictureRepository.GetById(id);
            if (null == picture) {
                return NotFound();
            }
            var viewModel = new EditPictureViewModel(picture);
            return View(viewModel);
        }

        [HttpPost, Authorize, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditPictureViewModel viewModel) {
            if (!ModelState.IsValid) {
                return View(viewModel);
            }
            var picture = await this.pictureRepository.GetById(id);
            if (null == picture || picture?.Id != id) {
                return NotFound();
            }
            if (viewModel.Title != picture.Title && await this.pictureRepository.IsTitleExisting(viewModel.Title)) {
                ModelState.AddModelError("Title", "Titel bereits vergeben.");
                return View(viewModel);
            }
            picture.UpdateFrom(viewModel);
            await this.pictureRepository.Update(picture);
            return RedirectToAction("List");
        }

        [HttpGet, AllowAnonymous]
        public async Task<IActionResult> List(ListViewModel viewModel) {
            viewModel.Pictures = await this.pictureRepository.GetAll(User.Identity.IsAuthenticated, viewModel.Occasion);
            return View(viewModel);
        }

        [HttpGet, AllowAnonymous]
        public async Task<IActionResult> Thumbnail(string pictureUrl) {
            var picture = await this.pictureRepository.GetByUrl(pictureUrl);
            if (null == picture) {
                return NotFound();
            }
            return File(picture.ThumbnailFile, picture.ContentType);
        }

    }

}

TortenkreationSHSBlog/Views/Pictures/Create.cshtml
@model TortenkreationSHSBlog.Models.CreatePictureViewModel

@{
    ViewData["Title"] = "Neues Foto";
}

<br />
<div class="row">
    <div class="col s12 m8 l8 offset-m2 offset-l2">
        <h4>@ViewData["Title"]</h4>
    </div>
</div>
<form method="post" asp-action="Create" asp-controller="Pictures" enctype="multipart/form-data">
    <div class="row">
        <div class="input-field col s12 m8 l8 offset-m2 offset-l2">
            <input type="text" asp-for="@Model.Title" data-length="50" required>
            <label for="Title">Titel</label>
            <span asp-validation-for="@Model.Title"></span>
        </div>
    </div>
    <div class="row">
        <div class="input-field col s12 m8 l8 offset-m2 offset-l2">
            <select asp-for="@Model.Occasion" asp-items="Html.GetEnumSelectList<Occasion>()" required>
                <option selected="selected" disabled>Bitte wählen</option>
            </select>
            <label>Anlass</label>
            <span asp-validation-for="@Model.Occasion"></span>
        </div>
    </div>
    <div class="row">
        <div class="input-field file-field col s12 m8 l8 offset-m2 offset-l2">
            <div class="btn waves-effect waves-light pink lighten-2">
                Foto
                <input type="file" asp-for="@Model.File" required>
            </div>
            <div class="file-path-wrapper">
                <input class="file-path" type="text">
            </div>
            <span asp-validation-for="@Model.File"></span>
        </div>
    </div>
    <div class="row">
        <div class="col s12 m8 l8 offset-m2 offset-l2">
            <p>
                <label>
                    <input type="checkbox" asp-for="@Model.IsPublished" />
                    <span>Veröffentlichen</span>
                </label>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col s12 m8 l8 offset-m2 offset-l2">
            <button class="btn waves-effect waves-light pink" type="submit" name="action">Speichern</button>
            <a class="btn waves-effect waves-light pink lighten-1" asp-route="list-pictures">Abbrechen</a>
        </div>
    </div>
</form>

TortenkreationSHSBlog/Views/Pictures/CreateOrEdit.cshtml
@model TortenkreationSHSBlog.Models.PictureViewModel

@{
    if (Model.IsDirty()) {
        //Edit
        ViewData["Title"] = "Foto bearbeiten: " + Model.Title;
        ViewData["Action"] = "Edit";
    } else {
        //Create
        ViewData["Title"] = "Neues Foto";
        ViewData["Action"] = "Create";
    }
}

<div class="row">
    <div class="col s12 m8 l8 offset-m2 offset-l2">
        <h4>@ViewData["Title"]</h4>
    </div>
</div>
@if (!string.IsNullOrWhiteSpace(Model.ValidationMessage)) {
    <div class="row">
        <div class="col s12 m8 l8 offset-m2 offset-l2">
            <p class="red-text darken-2">@Model.ValidationMessage</p>
        </div>
    </div>
}
<form method="post" asp-action="@ViewData["Action"]" asp-controller="Pictures" enctype="multipart/form-data">
    <div class="row">
        <div class="input-field col s12 m8 l8 offset-m2 offset-l2">
            <input type="text" id="picture_title" name="Title" asp-for="@Model.Title" data-length="@Model.TitleLength" required>
            <label for="title">Titel</label>
        </div>
    </div>
    <div class="row">
        <div class="input-field col s12 m8 l8 offset-m2 offset-l2">
            <select asp-for="@Model.SelectedOccasion" asp-items="Html.GetEnumSelectList<Occasion>()" required>
                <option selected="selected" disabled>Bitte wählen</option>
            </select>
            <label>Anlass</label>
        </div>
    </div>
    <div class="row">
        <div class="input-field file-field col s12 m8 l8 offset-m2 offset-l2">
            <div class="btn waves-effect waves-light pink lighten-2">
                Foto
                <input type="file" id="file" name="File" asp-for="@Model.File" required>
            </div>
            <div class="file-path-wrapper">
                <input class="file-path" type="text">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col s12 m8 l8 offset-m2 offset-l2">
            <button class="btn waves-effect waves-light pink lighten-2" type="submit" name="action">Speichern</button>
            <a class="btn waves-effect waves-light pink lighten-3" asp-route="list-pictures">Abbrechen</a>
        </div>
    </div>
</form>

TortenkreationSHSBlog/Views/Pictures/Delete.cshtml
@model TortenkreationSHSBlog.Models.EditPictureViewModel

@{
    ViewData["Title"] = "Foto '" + Model.Title + "' löschen";
}

<br />
<div class="row">
    <div class="col s12 m8 l8 offset-m2 offset-l2">
        <img src="@Model.ThumbnailUrl" alt="@Model.Title" width="200">
    </div>
</div>
<div class="row">
    <div class="col s12 m8 l8 offset-m2 offset-l2">
        Foto wirklich löschen?
    </div>
</div>
<div class="row">
    <div class="col s12 m8 l8 offset-m2 offset-l2">
        <form method="post" asp-action="Delete" asp-controller="Pictures">
            <button class="btn waves-effect waves-light pink" type="submit" name="action">Löschen</button>
            <a class="btn waves-effect waves-light pink lighten-1" asp-route="edit-picture" asp-route-id="@Model.Id">Abbrechen</a>
        </form>
    </div>
</div>

TortenkreationSHSBlog/Views/Pictures/Edit.cshtml
@model TortenkreationSHSBlog.Models.EditPictureViewModel

@{
    ViewData["Title"] = "Foto '" + Model.Title + "' bearbeiten";
}

<br />
<div class="row">
    <div class="col s12 m8 l8 offset-m2 offset-l2">
        <img src="@Model.ThumbnailUrl" alt="@Model.Title" width="200">
    </div>
</div>
<form method="post" asp-action="Edit" asp-controller="Pictures">
    <div class="row">
        <div class="input-field col s12 m8 l8 offset-m2 offset-l2">
            <input type="text" asp-for="@Model.Title" data-length="50" required>
            <label for="title">Titel</label>
            <span asp-validation-for="@Model.Title"></span>
        </div>
    </div>
    <div class="row">
        <div class="input-field col s12 m8 l8 offset-m2 offset-l2">
            <select asp-for="@Model.Occasion" asp-items="Html.GetEnumSelectList<Occasion>()" required>
                <option selected="selected" disabled>Bitte wählen</option>
            </select>
            <label>Anlass</label>
            <span asp-validation-for="@Model.Occasion"></span>
        </div>
    </div>
    <div class="row">
        <div class="col s12 m8 l8 offset-m2 offset-l2">
            <p>
                <label>
                    <input type="checkbox" asp-for="@Model.IsPublished" />
                    <span>Veröffentlichen</span>
                </label>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col s12 m8 l8 offset-m2 offset-l2">
            <button class="btn waves-effect waves-light pink" type="submit" name="action">Änderungen speichern</button>
            <a class="btn waves-effect waves-light pink" asp-route="delete-picture" asp-route-id="@Model.Id">Löschen</a>
            <a class="btn waves-effect waves-light pink lighten-1" asp-route="list-pictures">Abbrechen</a>
        </div>
    </div>
</form>

TortenkreationSHSBlog/Views/Pictures/List.cshtml
@model TortenkreationSHSBlog.Models.ListViewModel

@{
    ViewData["Title"] = "Tortengalerie";
}

<br />
<div class="container">
    <div class="row">
        <form method="get">
            <div class="col">
                <div class="input-field">
                    <select asp-for="@Model.Occasion" asp-items="Html.GetEnumSelectList<Occasion>()">
                        <option selected="selected" value="0">Alle</option>
                    </select>
                    <label>Anlass</label>
                </div>
            </div>
            <div class="col">
                <button class="btn pink lighten-1" type="submit">Filtern</button>
            </div>
        </form>
    </div>
    <div class="row">
        @foreach (var picture in Model.Pictures) {
            <div class="col s12 m6 l4">
                <div class="card grey lighten-5">
                    <div class="card-image">
                        <a href="/img/detail/@picture.GetUrl()">
                            <img src="/img/thumbnail/@picture.GetUrl()" alt="@picture.Title" />
                        </a>
                        @if (User.Identity.IsAuthenticated) {
                            <a class="btn-floating btn halfway-fab waves-effect waves-light pink lighten-2" asp-route="edit-picture" asp-route-id="@picture.Id"><i class="material-icons">edit</i></a>
                        }
                    </div>
                    <div class="card-content">
                        @if (picture.IsPublished) {
                            <p class="truncate">@picture.Title</p>
                        } else {
                            <p class="truncate"><span class="material-icons">lock</span> @picture.Title</p>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
    @if (User.Identity.IsAuthenticated) {
        <div class="fixed-action-btn">
            <a asp-route="create-picture" class="btn-floating btn-large waves-effect waves-light pink lighten-2">
                <i class="large material-icons">add</i>
            </a>
        </div>
    }
</div>